- name: Unix Tasks
  ansible.builtin.include_tasks: unix.yml
  when: ansible_facts['os_family'] not in ['Darwin', 'Windows'] and golang is defined | default([])

- name: Darwin Tasks
  ansible.builtin.include_tasks: darwin.yml
  when: ansible_facts['distribution'] == 'Darwin' and golang is defined
