
nerd_fonts: []

files:
  user:
  - { src: 'dotfiles/.vimrc', dest: '~/.vimrc' }
  - { src: 'dotfiles/.zshrc-linux', dest: '~/.zshrc' }
  - { src: 'dotfiles/.zshrc-common', dest: '~/.zshrc-common' }
  - { src: 'themes/oh-my-posh/kev.omp.json', dest: '~/.kev.omp.json' }
  root:
  - { src: 'dotfiles/.vimrc', dest: '/root/.vimrc' }
  - { src: 'dotfiles/.zshrc-linux', dest: '/root/.zshrc' }
  - { src: 'dotfiles/.zshrc-common', dest: '/root/.zshrc-common' }
  - { src: 'themes/oh-my-posh/kev.omp.json', dest: '/root/.kev.omp.json' }

firewall_rules:
  - { port: '22', proto: 'tcp', comment: 'SSH', from: '10.0.0.0/16' }

pi-gadget:
  dhcpcd:
    hostname: pi-gadget
    interface: usb0
    address: 100.0.0.10/24
    routes: 100.0.0.1
    nameservers:
      - 1.1.1.1
      - 8.8.8.8
      - 9.9.9.9
