# Default values for plex.

replicaCount: 1

image:
  repository: linuxserver/plex
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

# Plex claim token from https://plex.tv/claim
claimToken: ""

# Set the timezone of the plex server
timezone: UTC

plexPort: "32400"

service:
  type: ClusterIP
  port: 32400
  targetPort: 32400
  protocol: TCP

ingress:
  enabled: false
  className: "nginx"
  annotations: { cert-manager.io/cluster-issuer: "letsencrypt-prod" }
  hosts:
  - host: plex.example.com
    paths:
    - path: /
      pathType: Prefix
  tls:
  - secretName: plex-tls
    hosts:
    - plex.example.com

persistence:
  movies:
    storageClass: "local-storage"
    size: 100Gi
    accessMode: ReadWriteMany
  series:
    storageClass: "local-storage"
    size: 100Gi
    accessMode: ReadWriteMany
  seriesExt:
    storageClass: "local-storage"
    size: 100Gi
    accessMode: ReadWriteMany
  config:
    storageClass: "local-storage"
    size: 3Gi
    accessMode: ReadWriteMany

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
