provider:
  name: cloudflare

env:
- name: CF_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: cloudflare-api-token
      key: api-token

domainFilters:
- livingroom.cloud

managedRecordTypes:
- A
- AAAA
- CNAME
- MX
- TXT

policy: upsert-only
registry: txt
txtOwnerId: mini-cloud
txtPrefix: externaldns

extraArgs:
- --default-targets=174.44.105.210
- --force-default-targets

sources:
- service
- ingress
- crd

crd:
  create: true

logLevel: info
interval: 1m

serviceAccount:
  create: true

rbac:
  create: true

metrics:
  enabled: false
