- name: Download k9s .deb package
  get_url:
    url: https://github.com/derailed/k9s/releases/download/v0.32.5/k9s_linux_amd64.deb
    dest: "/tmp/k9s_linux_amd64.deb"

- name: Install k9s .deb package
  become: true
  ansible.builtin.apt:
    deb: "/tmp/k9s_linux_amd64.deb"
    state: present

- name: Remove k9s .deb package
  file:
    path: "/tmp/k9s_linux_amd64.deb"
    state: absent

