# vim:ft=ansible
- name: Unix Tasks
  ansible.builtin.include_tasks: unix.yml
  when: ansible_facts['distribution'] != 'Windows' and (lookup('vars', ansible_facts['os_family'] | lower).k3s is defined)
  tags: [k3s, get-kubeconfig]