- name: Provisions Local Machine
  hosts: local
  gather_facts: true
  
  roles:
    - { role: packages, tags: ['packages', 'casks'] }
    - { role: nerd-fonts, tags: ['nerd-fonts'] }
    - { role: files, tags: ['files'] }
    - { role: shell, tags: ['shell'] }
    - { role: golang, tags: ['go'] }
